package at.fhv.orchestraria.domain.model;

import at.fhv.orchestraria.domain.Imodel.IAdministrativeAssistant;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * @author generated by Intellij -  edited by Team C
 */

/*
 * Generated by IntelliJ
 */

@Entity
@Table(name = "administrativeAssistant", schema = "ni128610_1sql8")
public class AdministrativeAssistantEntity implements IAdministrativeAssistant, Serializable {
    private int userId;
    private String description;
    private UserEntity user;
    public static final String typeOrganisation = "Organisationsreferent";
    public static final String typeNote = "Notenwart";
    public static final String typeOrchestra = "Orchesterwart";

    @Id
    //@GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "userId")
    @Override
    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    @Basic
    @Column(name = "description")
    @Override
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AdministrativeAssistantEntity that = (AdministrativeAssistantEntity) o;
        return userId == that.userId &&
                Objects.equals(description, that.description);
    }

    @Override
    public int hashCode() {
        return Objects.hash(userId, description);
    }

    @OneToOne (cascade = CascadeType.MERGE)
    @JoinColumn(name = "userId", referencedColumnName = "userId", nullable = false)
    @Override
    public UserEntity getUser() {
        return user;
    }

    public void setUser(UserEntity user) {
        this.user = user;
    }
}
