package at.fhv.orchestraria.domain.model;

import at.fhv.orchestraria.domain.Imodel.IDutySectionMonthlySchedule;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * @author generated by Intellij -  edited by Team C
 */

/*
 * Generated by IntelliJ
 */

@Entity
@Table(name = "duty_sectionMonthlySchedule", schema = "ni128610_1sql8")
public class DutySectionMonthlyScheduleEntityC implements IDutySectionMonthlySchedule, Serializable {
    private int dutySectionMonthlyScheduleId;
    private DutyEntityC duty;
    private SectionMonthlyScheduleEntityC sectionMonthlySchedule;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "duty_sectionMonthlyScheduleId")
    @Override
    public int getDutySectionMonthlyScheduleId() {
        return dutySectionMonthlyScheduleId;
    }

    public void setDutySectionMonthlyScheduleId(int dutySectionMonthlyScheduleId) {
        this.dutySectionMonthlyScheduleId = dutySectionMonthlyScheduleId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        DutySectionMonthlyScheduleEntityC that = (DutySectionMonthlyScheduleEntityC) o;
        return dutySectionMonthlyScheduleId == that.dutySectionMonthlyScheduleId;
    }

    @Override
    public int hashCode() {
        return Objects.hash(dutySectionMonthlyScheduleId);
    }

    @ManyToOne
    @JoinColumn(name = "dutyId", referencedColumnName = "dutyId", nullable = false)
    public DutyEntityC getDuty() {
        return duty;
    }

    public void setDuty(DutyEntityC dutyByDutyId) {
        this.duty = dutyByDutyId;
    }

    @ManyToOne
    @JoinColumn(name = "sectionMonthlyScheduleId", referencedColumnName = "sectionMonthlyScheduleId", nullable = false)
    @Override
    public SectionMonthlyScheduleEntityC getSectionMonthlySchedule() {
        return sectionMonthlySchedule;
    }

    public void setSectionMonthlySchedule(SectionMonthlyScheduleEntityC sectionMonthlySchedule) {
        this.sectionMonthlySchedule = sectionMonthlySchedule;
    }
}
