package at.fhv.orchestraria.domain.model;

import at.fhv.orchestraria.domain.Imodel.IInstrumentCategoryMusician;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * @author generated by Intellij -  edited by Team C
 */

/*
 * Generated by IntelliJ
 */

@Entity
@Table(name = "instrumentCategory_musician", schema = "ni128610_1sql8")
public class InstrumentCategoryMusicianEntity implements IInstrumentCategoryMusician, Serializable {
    private int instrumentCategoryMusicianId;
    private InstrumentCategoryEntity instrumentCategory;
    private MusicianEntity musician;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "instrumentCategory_musicianId")
    @Override
    public int getInstrumentCategoryMusicianId() {
        return instrumentCategoryMusicianId;
    }

    public void setInstrumentCategoryMusicianId(int instrumentCategoryMusicianId) {
        this.instrumentCategoryMusicianId = instrumentCategoryMusicianId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        InstrumentCategoryMusicianEntity that = (InstrumentCategoryMusicianEntity) o;
        return instrumentCategoryMusicianId == that.instrumentCategoryMusicianId;
    }

    @Override
    public int hashCode() {
        return Objects.hash(instrumentCategoryMusicianId);
    }

    @ManyToOne
    @JoinColumn(name = "instrumentCategoryId", referencedColumnName = "instrumentCategoryId", nullable = false)
    @Override
    public InstrumentCategoryEntity getInstrumentCategory() {
        return instrumentCategory;
    }

    public void setInstrumentCategory(InstrumentCategoryEntity instrumentCategory) {
        this.instrumentCategory = instrumentCategory;
    }

    @ManyToOne
    @JoinColumn(name = "musicianId", referencedColumnName = "musicianId", nullable = false)
    @Override
    public MusicianEntity getMusician() {
        return musician;
    }

    public void setMusician(MusicianEntity musician) {
        this.musician = musician;
    }
}
