package at.fhv.orchestraria.domain.model;

import at.fhv.orchestraria.domain.Imodel.IInstrumentCategoryMusician;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * @author generated by Intellij -  edited by Team C
 */

/*
 * Generated by IntelliJ
 */

@Entity
@Table(name = "instrumentCategory_musician", schema = "ni128610_1sql8")
public class InstrumentCategoryMusicianEntityC implements IInstrumentCategoryMusician, Serializable {
    private int instrumentCategoryMusicianId;
    private InstrumentCategoryEntityC instrumentCategory;
    private MusicianEntityC musician;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "instrumentCategory_musicianId")
    @Override
    public int getInstrumentCategoryMusicianId() {
        return instrumentCategoryMusicianId;
    }

    public void setInstrumentCategoryMusicianId(int instrumentCategoryMusicianId) {
        this.instrumentCategoryMusicianId = instrumentCategoryMusicianId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        InstrumentCategoryMusicianEntityC that = (InstrumentCategoryMusicianEntityC) o;
        return instrumentCategoryMusicianId == that.instrumentCategoryMusicianId;
    }

    @Override
    public int hashCode() {
        return Objects.hash(instrumentCategoryMusicianId);
    }

    @ManyToOne
    @JoinColumn(name = "instrumentCategoryId", referencedColumnName = "instrumentCategoryId", nullable = false)
    @Override
    public InstrumentCategoryEntityC getInstrumentCategory() {
        return instrumentCategory;
    }

    public void setInstrumentCategory(InstrumentCategoryEntityC instrumentCategory) {
        this.instrumentCategory = instrumentCategory;
    }

    @ManyToOne
    @JoinColumn(name = "musicianId", referencedColumnName = "musicianId", nullable = false)
    @Override
    public MusicianEntityC getMusician() {
        return musician;
    }

    public void setMusician(MusicianEntityC musician) {
        this.musician = musician;
    }
}
