package at.fhv.orchestraria.domain.model;

import at.fhv.orchestraria.domain.Imodel.IMusicianRoleMusician;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * @author generated by Intellij -  edited by Team C
 */

/*
 * Generated by IntelliJ
 */

@Entity
@Table(name = "musicianRole_musician", schema = "ni128610_1sql8")
public class MusicianRoleMusicianEntityC implements IMusicianRoleMusician, Serializable {
    private int musicianRoleMusicianId;
    private MusicianRoleEntityC musicianRole;
    private MusicianEntityC musician;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "musicianRole_musicianId")
    @Override
    public int getMusicianRoleMusicianId() {
        return musicianRoleMusicianId;
    }

    public void setMusicianRoleMusicianId(int musicianRoleMusicianId) {
        this.musicianRoleMusicianId = musicianRoleMusicianId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        MusicianRoleMusicianEntityC that = (MusicianRoleMusicianEntityC) o;
        return musicianRoleMusicianId == that.musicianRoleMusicianId;
    }

    @Override
    public int hashCode() {
        return Objects.hash(musicianRoleMusicianId);
    }

    @ManyToOne(cascade = CascadeType.MERGE)
    @JoinColumn(name = "musicianRoleId", referencedColumnName = "musicianRoleId")
    @Override
    public MusicianRoleEntityC getMusicianRole() {
        return musicianRole;
    }

    public void setMusicianRole(MusicianRoleEntityC musicianRole) {
        this.musicianRole = musicianRole;
    }

    @ManyToOne(cascade = CascadeType.MERGE)
    @JoinColumn(name = "musicianId", referencedColumnName = "musicianId")
    @Override
    public MusicianEntityC getMusician() {
        return musician;
    }

    public void setMusician(MusicianEntityC musician) {
        this.musician = musician;
    }
}
