package at.fhv.orchestraria.domain.model;

import at.fhv.orchestraria.domain.Imodel.IPositiveWish;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * @author generated by Intellij -  edited by Team C
 */

/*
 * Generated by IntelliJ
 */

@Entity
@Table(name = "positiveWish", schema = "ni128610_1sql8")
public class PositiveWishEntity implements IPositiveWish, Serializable {
    private int positiveWishId;
    private String description;
    private SeriesOfPerformancesEntity seriesOfPerformances;
    private MusicianEntity musician;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "positiveWishId")
    @Override
    public int getPositiveWishId() {
        return positiveWishId;
    }

    public void setPositiveWishId(int positiveWishId) {
        this.positiveWishId = positiveWishId;
    }

    @Basic
    @Column(name = "description")
    @Override
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PositiveWishEntity that = (PositiveWishEntity) o;
        return positiveWishId == that.positiveWishId &&
                Objects.equals(description, that.description);
    }

    @Override
    public int hashCode() {
        return Objects.hash(positiveWishId, description);
    }

    @ManyToOne
    @JoinColumn(name = "seriesOfPerformancesId", referencedColumnName = "seriesOfPerformancesId", nullable = false)
    @Override
    public SeriesOfPerformancesEntity getSeriesOfPerformances() {
        return seriesOfPerformances;
    }

    public void setSeriesOfPerformances(SeriesOfPerformancesEntity seriesOfPerformances) {
        this.seriesOfPerformances = seriesOfPerformances;
    }

    @ManyToOne
    @JoinColumn(name = "musicianId", referencedColumnName = "musicianId", nullable = false)
    @Override
    public MusicianEntity getMusician() {
        return musician;
    }

    public void setMusician(MusicianEntity musician) {
        this.musician = musician;
    }
}
