package at.fhv.orchestraria.domain.model;

import at.fhv.orchestraria.domain.Imodel.ISectionInstrumentCategory;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * @author generated by Intellij -  edited by Team C
 */

/*
 * Generated by IntelliJ
 */

@Entity
@Table(name = "section_instrumentCategory", schema = "ni128610_1sql8")
public class SectionInstrumentCategoryEntity implements ISectionInstrumentCategory, Serializable {
    private int sectionInstrumentCategoryId;
    private InstrumentCategoryEntity instrumentCategory;
    private SectionEntity section;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "section_instrumentCategoryId")
    @Override
    public int getSectionInstrumentCategoryId() {
        return sectionInstrumentCategoryId;
    }

    public void setSectionInstrumentCategoryId(int sectionInstrumentCategoryId) {
        this.sectionInstrumentCategoryId = sectionInstrumentCategoryId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SectionInstrumentCategoryEntity that = (SectionInstrumentCategoryEntity) o;
        return sectionInstrumentCategoryId == that.sectionInstrumentCategoryId;
    }

    @Override
    public int hashCode() {
        return Objects.hash(sectionInstrumentCategoryId);
    }

    @ManyToOne
    @JoinColumn(name = "instrumentCategoryId", referencedColumnName = "instrumentCategoryId", nullable = false)
    @Override
    public InstrumentCategoryEntity getInstrumentCategory() {
        return instrumentCategory;
    }

    public void setInstrumentCategory(InstrumentCategoryEntity instrumentCategory) {
        this.instrumentCategory = instrumentCategory;
    }

    @ManyToOne
    @JoinColumn(name = "sectionId", referencedColumnName = "sectionId", nullable = false)
    @Override
    public SectionEntity getSection() {
        return section;
    }

    public void setSection(SectionEntity section) {
        this.section = section;
    }
}
