package at.fhv.orchestraria.domain.model;

import at.fhv.orchestraria.domain.Imodel.ISeriesOfPerformancesMusicalPiece;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * @author generated by Intellij -  edited by Team C
 */

/*
 * Generated by IntelliJ
 */

@Entity
@Table(name = "seriesOfPerformances_musicalPiece", schema = "ni128610_1sql8")
public class SeriesOfPerformancesMusicalPieceEntityC implements ISeriesOfPerformancesMusicalPiece, Serializable {
    private int seriesOfPerformancesMusicalPieceId;
    private MusicalPieceEntityC musicalPiece;
    private SeriesOfPerformancesEntityC seriesOfPerformances;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "seriesOfPerformances_musicalPieceId")
    @Override
    public int getSeriesOfPerformancesMusicalPieceId() {
        return seriesOfPerformancesMusicalPieceId;
    }

    public void setSeriesOfPerformancesMusicalPieceId(int seriesOfPerformancesMusicalPieceId) {
        this.seriesOfPerformancesMusicalPieceId = seriesOfPerformancesMusicalPieceId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SeriesOfPerformancesMusicalPieceEntityC that = (SeriesOfPerformancesMusicalPieceEntityC) o;
        return seriesOfPerformancesMusicalPieceId == that.seriesOfPerformancesMusicalPieceId;
    }

    @Override
    public int hashCode() {
        return Objects.hash(seriesOfPerformancesMusicalPieceId);
    }

    @ManyToOne
    @JoinColumn(name = "musicalPieceId", referencedColumnName = "musicalPieceId")
    public MusicalPieceEntityC getMusicalPiece() {
        return musicalPiece;
    }

    public void setMusicalPiece(MusicalPieceEntityC musicalPieceByMusicalPieceId) {
        this.musicalPiece = musicalPieceByMusicalPieceId;
    }

    @ManyToOne
    @JoinColumn(name = "seriesOfPerformancesId", referencedColumnName = "seriesOfPerformancesId")
    @Override
    public SeriesOfPerformancesEntityC getSeriesOfPerformances() {
        return seriesOfPerformances;
    }

    public void setSeriesOfPerformances(SeriesOfPerformancesEntityC seriesOfPerformances) {
        this.seriesOfPerformances = seriesOfPerformances;
    }
}
