package at.fhv.orchestraria.domain.model;

import at.fhv.orchestraria.domain.Imodel.ISeriesOfPerformancesMusicalPiece;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * @author generated by Intellij -  edited by Team C
 */

/*
 * Generated by IntelliJ
 */

@Entity
@Table(name = "seriesOfPerformances_musicalPiece", schema = "ni128610_1sql8")
public class SeriesOfPerformancesMusicalPieceEntity implements ISeriesOfPerformancesMusicalPiece, Serializable {
    private int seriesOfPerformancesMusicalPieceId;
    private MusicalPieceEntity musicalPiece;
    private SeriesOfPerformancesEntity seriesOfPerformances;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "seriesOfPerformances_musicalPieceId")
    @Override
    public int getSeriesOfPerformancesMusicalPieceId() {
        return seriesOfPerformancesMusicalPieceId;
    }

    public void setSeriesOfPerformancesMusicalPieceId(int seriesOfPerformancesMusicalPieceId) {
        this.seriesOfPerformancesMusicalPieceId = seriesOfPerformancesMusicalPieceId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SeriesOfPerformancesMusicalPieceEntity that = (SeriesOfPerformancesMusicalPieceEntity) o;
        return seriesOfPerformancesMusicalPieceId == that.seriesOfPerformancesMusicalPieceId;
    }

    @Override
    public int hashCode() {
        return Objects.hash(seriesOfPerformancesMusicalPieceId);
    }

    @ManyToOne
    @JoinColumn(name = "musicalPieceId", referencedColumnName = "musicalPieceId")
    public MusicalPieceEntity getMusicalPiece() {
        return musicalPiece;
    }

    public void setMusicalPiece(MusicalPieceEntity musicalPieceByMusicalPieceId) {
        this.musicalPiece = musicalPieceByMusicalPieceId;
    }

    @ManyToOne
    @JoinColumn(name = "seriesOfPerformancesId", referencedColumnName = "seriesOfPerformancesId")
    @Override
    public SeriesOfPerformancesEntity getSeriesOfPerformances() {
        return seriesOfPerformances;
    }

    public void setSeriesOfPerformances(SeriesOfPerformancesEntity seriesOfPerformances) {
        this.seriesOfPerformances = seriesOfPerformances;
    }
}
