trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SonarQubePrepare@4
  inputs:
    SonarQube: '***REMOVED***'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=***REMOVED***
      sonar.projectName=***REMOVED***
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    checkStyleRunAnalysis: true
    tasks: 'build'
    sonarQubeRunAnalysis: true
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/jacocoTestReport.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/jacoco/test/**'
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'    